# ============================
# Project
# ============================

[project]
name = "pyscx"
version = "2.0.0"
readme = "README.md"
license = { text = "LICENSE" }
description = "Library for interacting with the STALCRAFT: X API"
authors = [
    { name = "Oidaho", email = "oidaho.main@yandex.ru" }
]
keywords = [
    "api",
    "library",
    "eapi",
    "stalcraft",
    "package",
]
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Games/Entertainment",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Natural Language :: English",
    "Natural Language :: Russian",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]
requires-python = "==3.13.*"
packages = [
    "pyscx"
]
dependencies = [
    "requests (>=2.32.3,<3.0.0)",
    "cachetools (>=5.5.1,<6.0.0)",
    "pydantic (>=2.10.6,<3.0.0)",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1,<2",
]
test = [
    "pytest>=8.3.4,<9",
]
docs = [
    "sphinx>=8.1.3,<9",
    "sphinx-rtd-theme>=3.0.2,<4",
]

[project.urls]
repository = "https://github.com/Oidaho/pyscx"
"Bug Tracker" = "https://github.com/Oidaho/pyscx/issues"
documentation = "https://Oidaho.github.io/pyscx/"

# ============================
# UV 
# ============================

[tool.uv]
package = true
default-groups = "all"

[tool.uv.build-backend]
module-name = "pyscx"
module-root = ""

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

# ============================
# Ruff 
# ============================

[tool.ruff]
line-length = 88
target-version = "py313"

# ============================
# Pytest 
# ============================

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_color = true  
testpaths = ["tests"]
python_files = ["test_*.py"]
console_output_style = "progress"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
addopts = "--disable-warnings"
norecursedirs = [
    ".venv",
    "build",
    "dist",
    "__pycache__"
]

